language: java
jdk:
  - openjdk8
  
  
before_script:
  - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'` 
  
before_deploy:
   - mvn p2:site

deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-p2.sh
    on:
      repo: korpling/pepper
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-p2.sh
    on:
      repo: korpling/pepper
      branch: feature/p2-site
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true