var namespaceorg_1_1corpus__tools_1_1pepper_1_1cli_1_1exceptions =
[
    [ "PepperOSGiException", "classorg_1_1corpus__tools_1_1pepper_1_1cli_1_1exceptions_1_1_pepper_o_s_gi_exception.html", "classorg_1_1corpus__tools_1_1pepper_1_1cli_1_1exceptions_1_1_pepper_o_s_gi_exception" ],
    [ "PepperOSGiFrameworkPluginException", "classorg_1_1corpus__tools_1_1pepper_1_1cli_1_1exceptions_1_1_pepper_o_s_gi_framework_plugin_exception.html", "classorg_1_1corpus__tools_1_1pepper_1_1cli_1_1exceptions_1_1_pepper_o_s_gi_framework_plugin_exception" ],
    [ "PepperPropertyException", "classorg_1_1corpus__tools_1_1pepper_1_1cli_1_1exceptions_1_1_pepper_property_exception.html", "classorg_1_1corpus__tools_1_1pepper_1_1cli_1_1exceptions_1_1_pepper_property_exception" ]
];