<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pepperModules"
    nsURI="de.hu_berlin.german.korpling.saltnpepper.pepper.pepperModules" nsPrefix="pepperModules">
  <eClassifiers xsi:type="ecore:EClass" name="PepperModule">
    <eOperations name="start" eExceptions="#//PepperModuleException"/>
    <eOperations name="start" eExceptions="#//PepperModuleException">
      <eParameters name="sElementId" eType="#//SElementId"/>
    </eOperations>
    <eOperations name="end" eExceptions="#//PepperModuleException"/>
    <eOperations name="setLogService">
      <eParameters name="logService" eType="#//LogService"/>
    </eOperations>
    <eOperations name="unsetLogService">
      <eParameters name="logService" eType="#//LogService"/>
    </eOperations>
    <eOperations name="getLogService" eType="#//LogService"/>
    <eOperations name="getProgress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject">
      <eParameters name="sDocumentId" eType="#//SElementId"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperModuleController"
        eType="#//PepperModuleController" eOpposite="#//PepperModuleController/pepperModule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saltProject" lowerBound="1"
        eType="#//SaltProject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returningMode" eType="#//RETURNING_MODE"
        changeable="false" defaultValueLiteral="PUT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sCorpusGraph" lowerBound="1"
        eType="#//SCorpusGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resources" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temproraries" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistenceConnector" eType="#//PersistenceConnector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specialParams" eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperImporter" eSuperTypes="#//PepperModule">
    <eOperations name="importCorpusStructure" eExceptions="#//PepperModuleException">
      <eParameters name="corpusGraph" eType="#//SCorpusGraph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedFormats" lowerBound="1"
        upperBound="-1" eType="#//FormatDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corpusDefinition" lowerBound="1"
        eType="#//CorpusDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperExporter" eSuperTypes="#//PepperModule">
    <eOperations name="createFolderStructure">
      <eParameters name="sElementId" eType="#//SElementId"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedFormats" lowerBound="1"
        upperBound="-1" eType="#//FormatDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corpusDefinition" lowerBound="1"
        eType="#//CorpusDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormatDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatReference" eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="CorpusDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="corpusPath" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatDefinition" eType="#//FormatDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperModuleController" abstract="true"
      interface="true">
    <eOperations name="put">
      <eParameters name="sElementId" eType="#//SElementId"/>
    </eOperations>
    <eOperations name="get" eType="#//SElementId"/>
    <eOperations name="finish">
      <eParameters name="sElementId" eType="#//SElementId"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperModule" eType="#//PepperModule"
        containment="true" eOpposite="#//PepperModule/pepperModuleController"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SCorpusGraph" instanceClassName="de.hu_berlin.german.korpling.saltnpepper.salt.saltCommon.sCorpusStructure.SCorpusGraph"/>
  <eClassifiers xsi:type="ecore:EDataType" name="SaltProject" instanceClassName="de.hu_berlin.german.korpling.saltnpepper.salt.saltCommon.SaltProject"/>
  <eClassifiers xsi:type="ecore:EDataType" name="SElementId" instanceClassName="de.hu_berlin.german.korpling.saltnpepper.salt.saltCore.SElementId"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperModuleException" instanceClassName="de.hu_berlin.german.korpling.saltnpepper.pepper.pepperExceptions.PepperModuleException"/>
  <eClassifiers xsi:type="ecore:EEnum" name="RETURNING_MODE">
    <eLiterals name="FINISH"/>
    <eLiterals name="PUT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperManipulator" eSuperTypes="#//PepperModule"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EPackage" instanceClassName="org.eclipse.emf.ecore.EPackage"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ResourceFactory" instanceClassName="org.eclipse.emf.ecore.resource.impl.ResourceFactoryImpl"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionFactoryPair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceFactory" eType="#//ResourceFactory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersistenceConnector">
    <eOperations name="save" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource">
      <eParameters name="modelObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="modelURI" eType="#//URI"/>
    </eOperations>
    <eOperations name="getResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource">
      <eParameters name="resourceURI" eType="#//URI"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionFactoryPairs"
        upperBound="-1" eType="#//ExtensionFactoryPair"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="LogService" instanceClassName="org.osgi.service.log.LogService"/>
  <eSubpackages name="xsltModules" nsURI="xsltModules" nsPrefix="xsltModules">
    <eClassifiers xsi:type="ecore:EClass" name="PepperXSLTExporter" eSuperTypes="#//PepperExporter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="xsltTransformer" eType="#//xsltModules/XSLTTransformer"
          volatile="true" transient="true" derived="true" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSLTTransformer" eSuperTypes="#//PersistenceConnector">
      <eOperations name="transform">
        <eParameters name="sourceURI" eType="#//URI"/>
        <eParameters name="targetURI" eType="#//URI"/>
        <eParameters name="xsltURI" eType="#//URI"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
