<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pepperParams"
    nsURI="de.hu_berlin.german.korpling.saltnpepper.pepper.pepperParams" nsPrefix="pepperParams">
  <eClassifiers xsi:type="ecore:EClass" name="ModuleParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specialParams" eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImporterParams" eSuperTypes="#//ModuleParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourcePath" eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperParams">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJobParams" upperBound="-1"
        eType="#//PepperJobParams" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperJobParams">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importerParams" upperBound="-1"
        eType="#//ImporterParams" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleParams" upperBound="-1"
        eType="#//ModuleParams" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exporterParams" upperBound="-1"
        eType="#//ExporterParams" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExporterParams" eSuperTypes="#//ModuleParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationPath" eType="#//URI"/>
  </eClassifiers>
</ecore:EPackage>
