<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pepperFW"
    nsURI="de.hub.corpling.pepper.PepperFW" nsPrefix="pepperFW">
  <eClassifiers xsi:type="ecore:EClass" name="PepperConverter">
    <eOperations name="setPepperParams">
      <eParameters name="pepperParamUri" eType="#//URI"/>
    </eOperations>
    <eOperations name="start" eExceptions="#//PepperException"/>
    <eOperations name="startPepperConvertJob" eExceptions="#//PepperException">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperModuleResolver" lowerBound="1"
        eType="#//PepperModuleResolver" unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperParams" eType="#//PepperParams"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJobs" upperBound="-1"
        eType="#//PepperJob" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJ2CMonitors" upperBound="-1"
        eType="#//PepperFinishableMonitor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="properties" eType="#//Properties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperParamsURI" eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperModuleResolver">
    <eOperations name="getPepperImporter" eType="ecore:EClass ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//PepperImporter">
      <eParameters name="pepperImporterParams" eType="#//PepperImporterParams"/>
    </eOperations>
    <eOperations name="getPepperManipulator" eType="ecore:EClass ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//PepperManipulator">
      <eParameters name="pepperModuleParams" eType="#//PepperModuleParams"/>
    </eOperations>
    <eOperations name="getPepperExporter" eType="ecore:EClass ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//PepperExporter">
      <eParameters name="pepperExporterParams" eType="#//PepperExporterParams"/>
    </eOperations>
    <eOperations name="addPepperImporterComponentFactory">
      <eParameters name="pepperImporterComponentFactory" eType="#//ComponentFactory"/>
    </eOperations>
    <eOperations name="removePepperImporterComponentFactory">
      <eParameters name="pepperImporterComponentFactory" eType="#//ComponentFactory"/>
    </eOperations>
    <eOperations name="addPepperManipulatorComponentFactory">
      <eParameters name="pepperManipulatorComponentFactory" eType="#//ComponentFactory"/>
    </eOperations>
    <eOperations name="removePepperManipulatorComponentFactory">
      <eParameters name="pepperManipulatorComponentFactory" eType="#//ComponentFactory"/>
    </eOperations>
    <eOperations name="addPepperExporterComponentFactory">
      <eParameters name="pepperExporterComponentFactory" eType="#//ComponentFactory"/>
    </eOperations>
    <eOperations name="removePepperExporterComponentFactory">
      <eParameters name="pepperExporterComponentFactory" eType="#//ComponentFactory"/>
    </eOperations>
    <eOperations name="getPepperImporters" upperBound="-1" eType="#//PepperImporter"/>
    <eOperations name="getPepperManipulators" upperBound="-1" eType="ecore:EClass ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//PepperManipulator"/>
    <eOperations name="getPepperExporters" upperBound="-1" eType="#//PepperExporter"/>
    <eOperations name="getStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperImporterComponentFactories"
        upperBound="-1" eType="#//ComponentFactory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperManipulatorComponentFactories"
        upperBound="-1" eType="#//ComponentFactory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperExporterComponentFactories"
        upperBound="-1" eType="#//ComponentFactory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temprorariesPropertyName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="PepperModuleResolver.TemprorariesURI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourcesPropertyName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="PepperModuleResolver.ResourcesURI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BundleContext" instanceClassName="org.osgi.framework.BundleContext"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperModule" instanceClassName="de.hub.corpling.pepper.pepperInterface.PepperModule"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperImporter" instanceClassName="de.hub.corpling.pepper.pepperInterface.PepperImporter"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperExporter" instanceClassName="de.hub.corpling.pepper.pepperInterface.PepperExporter"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperParams" instanceClassName="de.hub.corpling.pepper.pepperParams.PepperParams"/>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperImporterParams" instanceClassName="de.hub.corpling.pepper.pepperParams.ImporterParams"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperModuleParams" instanceClassName="de.hub.corpling.pepper.pepperParams.ModuleParams"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperExporterParams" instanceClassName="de.hub.corpling.pepper.pepperParams.ExporterParams"/>
  <eClassifiers xsi:type="ecore:EClass" name="PepperJob" eSuperTypes="#//Runnable">
    <eOperations name="start" eExceptions="#//PepperModuleException #//PepperConvertException"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperImporters" lowerBound="1"
        upperBound="-1" eType="#//PepperImporter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperModules" upperBound="-1"
        eType="#//PepperModule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pepperExporters" lowerBound="1"
        upperBound="-1" eType="#//PepperExporter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperModuleControllers"
        upperBound="-1" eType="#//PepperModuleController" containment="true" eOpposite="#//PepperModuleController/pepperJob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperM2MMonitors" upperBound="-1"
        eType="#//PepperQueuedMonitor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperM2JMonitors" upperBound="-1"
        eType="#//PepperFinishableMonitor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saltProject" lowerBound="1"
        eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SaltProject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJ2CMonitor" eType="#//PepperFinishableMonitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJobLogger" eType="#//PepperJobLogger"
        eOpposite="#//PepperJobLogger/pepperJob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperDocumentController"
        eType="#//PepperDocumentController" containment="true" eOpposite="#//PepperDocumentController/pepperJobController"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="properties" eType="#//Properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperModuleController" eSuperTypes="../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//PepperModuleController #//Runnable">
    <eOperations name="start" eExceptions="#//PepperModuleException"/>
    <eOperations name="importCorpusStructure" eExceptions="#//PepperConvertException">
      <eParameters name="sCorpusGraph" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SCorpusGraph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJob" eType="#//PepperJob"
        eOpposite="#//PepperJob/pepperModuleControllers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPepperModuleMonitors"
        upperBound="-1" eType="#//PepperQueuedMonitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPepperModuleMonitors"
        upperBound="-1" eType="#//PepperQueuedMonitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperM2JMonitor" eType="#//PepperFinishableMonitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PepperJobLogger" eType="#//PepperJobLogger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperDocumentController"
        eType="#//PepperDocumentController" eOpposite="#//PepperDocumentController/pepperModuleControllers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Runnable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PepperQueuedMonitor" eSuperTypes="#//PepperMonitor">
    <eOperations name="put">
      <eParameters name="sElementId" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
    </eOperations>
    <eOperations name="get" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderQueue" eType="#//ConcurrentLinkedQueue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="empty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperFinishableMonitor" eSuperTypes="#//PepperMonitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="PepperMonitor">
    <eOperations name="finish"/>
    <eOperations name="waitUntilFinished"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finished" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptions" upperBound="-1"
        eType="#//PepperException"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ConcurrentLinkedQueue" instanceClassName="java.util.concurrent.ConcurrentLinkedQueue"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperModuleException" instanceClassName="de.hub.corpling.pepper.pepperExceptions.PepperModuleException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperConvertException" instanceClassName="de.hub.corpling.pepper.pepperExceptions.PepperConvertException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PepperException" instanceClassName="de.hub.corpling.pepper.pepperExceptions.PepperException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ComponentFactory" instanceClassName="org.osgi.service.component.ComponentFactory"/>
  <eClassifiers xsi:type="ecore:EClass" name="PepperJobLogger">
    <eOperations name="setLogService">
      <eParameters name="logService" eType="#//LogService"/>
    </eOperations>
    <eOperations name="getLogService" eType="#//LogService"/>
    <eOperations name="logStatus">
      <eParameters name="sElementId" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
      <eParameters name="status" eType="#//PEPPER_SDOCUMENT_STATUS"/>
      <eParameters name="moduleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJob" eType="#//PepperJob"
        eOpposite="#//PepperJob/pepperJobLogger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="LogService" instanceClassName="org.osgi.service.log.LogService"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PEPPER_SDOCUMENT_STATUS">
    <eLiterals name="NOT_STARTED"/>
    <eLiterals name="IN_PROCESS" value="1"/>
    <eLiterals name="COMPLETED" value="2"/>
    <eLiterals name="DELETED" value="3"/>
    <eLiterals name="FAILED" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PepperDocumentController">
    <eOperations name="observeSDocument">
      <eParameters name="sDocumentId" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
    </eOperations>
    <eOperations name="getObservedSDocuments" upperBound="-1" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
    <eOperations name="setSDocumentStatus">
      <eParameters name="sDocumentId" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
      <eParameters name="moduleController" eType="#//PepperModuleController"/>
      <eParameters name="status" eType="#//PEPPER_SDOCUMENT_STATUS"/>
    </eOperations>
    <eOperations name="getStatus4Print" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getStatus" eType="#//PEPPER_SDOCUMENT_STATUS">
      <eParameters name="sDocumentId" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
    </eOperations>
    <eOperations name="getStatus" eType="#//PEPPER_SDOCUMENT_STATUS">
      <eParameters name="sDocumentId" eType="ecore:EDataType ../../de.hub.corpling.pepper.PepperInterface/model/pepperInterface.ecore#//SElementId"/>
      <eParameters name="pepperModuleController" eType="#//PepperModuleController"/>
    </eOperations>
    <eOperations name="finish"/>
    <eOperations name="setLogService">
      <eParameters name="logService" eType="#//LogService"/>
    </eOperations>
    <eOperations name="getLogService" eType="#//LogService"/>
    <eOperations name="waitForSDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperModuleControllers"
        upperBound="-1" eType="#//PepperModuleController" eOpposite="#//PepperModuleController/pepperDocumentController"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pepperJobController" eType="#//PepperJob"
        eOpposite="#//PepperJob/pepperDocumentController"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="REMOVE_SDOCUMENT_AFTER_PROCESSING"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="COMPUTE_PERFORMANCE" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AMOUNT_OF_COMPUTABLE_SDOCUMENTS"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        volatile="true" transient="true" defaultValueLiteral="10" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentAmountOfSDocuments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Properties" instanceClassName="java.util.Properties"/>
</ecore:EPackage>
